title: Project
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content_description
        field:
          input_type: text
          character_limit: 160
          antlers: false
          display: 'Content Description'
          type: text
          icon: text
          instructions: 'Describe this project in 150-160 characters'
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
      -
        handle: image
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          instructions: 'Will be displayed as featured image on post, and used as post thumbnail.'
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
          folder: images/projects/earth-sessions
      -
        handle: client
        field:
          mode: default
          create: true
          display: Client
          type: entries
          icon: entries
          instructions: 'Link the client associated with this project'
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
          max_items: 1
          collections:
            - clients
      -
        import: project_builder
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: date
        field:
          type: date
          required: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - posts
          max_items: 1
          listable: false
          localizable: true
  SEO:
    display: SEO
    fields:
      -
        handle: social_image
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          instructions: "If not set, the general image will be used. It's best to use an image with a 1.91:1 aspect ratio that is at least 1200px wide for universal support. The image will be resized to 1200 width."
          localizable: true
          listable: hidden
          display: Image
          instructions_position: above
          visibility: visible
          show_filename: true
      -
        handle: seo
        field:
          type: seo_pro
          listable: false
          display: SEO
